### ISSUE TITLE
 The domain has expired

### ISSUE THREAD

**Issue by oyajun** [niyeradori/QuickSmith-Web#2]
[quicksmith.online](https://quicksmith.online/) has expired.
Quick Smith Web has been now unavailable.
Could you buy this domain again or unlink the custom domain?

Now I made the fork of this repository and I have hosted it on Github Pages.
This page will be hosted until solving this problem.
https://oyajun.com/QuickSmith-Web

**Comment by maheshbrahmi** [comment]
I have renewed it. Thanks.
